In [154]:
import numpy as np
import pennylane as qml
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [155]:
df = pd.read_csv("DatasetExos.csv" ,delimiter="," )
df

ep (ms)     Acc_x     Acc_y     Acc_z  Gyro_x  Gyro_y  \
0     2019-01-11 15:08:05.200  0.013500  0.977000 -0.071000 -1.8904  2.4392   
1     2019-01-11 15:08:05.400 -0.001500  0.970500 -0.079500 -1.6826 -0.8904   
2     2019-01-11 15:08:05.600  0.001333  0.971667 -0.064333  2.5608 -0.2560   
3     2019-01-11 15:08:05.800 -0.024000  0.957000 -0.073500  8.0610 -4.5244   
4     2019-01-11 15:08:06.000 -0.028000  0.957667 -0.115000  2.4390 -1.5486   
...                       ...       ...       ...       ...     ...     ...   
9004  2019-01-20 17:33:27.000 -0.048000 -1.041500 -0.076500  1.4146 -5.6218   
9005  2019-01-20 17:33:27.200 -0.037000 -1.030333 -0.053333 -2.7684 -0.5854   
9006  2019-01-20 17:33:27.400 -0.060000 -1.031000 -0.082000  2.8416 -5.1342   
9007  2019-01-20 17:33:27.600 -0.038667 -1.025667 -0.044667 -0.2318  0.2562   
9008  2019-01-20 17:33:27.800 -0.044000 -1.034000 -0.059000  1.0980 -4.0240   

      Gyro_z ID Exercise Category   Set  
0     0.9388  B    bench    heavy  30.0  
1     2.1708  B    bench    heavy  30.0  
2    -1.4146  B    bench    heavy  30.0  
3    -2.0730  B    bench    heavy  30.0  
4    -3.6098  B    bench    heavy  30.0  
...      ... ..      ...      ...   ...  
9004  0.2926  E      row   medium  40.0  
9005  2.2440  E      row   medium  40.0  
9006 -0.1220  E      row   medium  40.0  
9007  1.1220  E      row   medium  40.0  
9008  0.9760  E      row   medium  40.0  

[9009 rows x 11 columns]

In [156]:
df.columns

Index(['ep (ms)', 'Acc_x', 'Acc_y', 'Acc_z', 'Gyro_x', 'Gyro_y', 'Gyro_z',
       'ID', 'Exercise', 'Category', 'Set'],
      dtype='object')

In [157]:
df = df.drop(columns=["ep (ms)" , "Exercise"  , "ID" , "Category"])
df

Acc_x     Acc_y     Acc_z  Gyro_x  Gyro_y  Gyro_z   Set
0     0.013500  0.977000 -0.071000 -1.8904  2.4392  0.9388  30.0
1    -0.001500  0.970500 -0.079500 -1.6826 -0.8904  2.1708  30.0
2     0.001333  0.971667 -0.064333  2.5608 -0.2560 -1.4146  30.0
3    -0.024000  0.957000 -0.073500  8.0610 -4.5244 -2.0730  30.0
4    -0.028000  0.957667 -0.115000  2.4390 -1.5486 -3.6098  30.0
...        ...       ...       ...     ...     ...     ...   ...
9004 -0.048000 -1.041500 -0.076500  1.4146 -5.6218  0.2926  40.0
9005 -0.037000 -1.030333 -0.053333 -2.7684 -0.5854  2.2440  40.0
9006 -0.060000 -1.031000 -0.082000  2.8416 -5.1342 -0.1220  40.0
9007 -0.038667 -1.025667 -0.044667 -0.2318  0.2562  1.1220  40.0
9008 -0.044000 -1.034000 -0.059000  1.0980 -4.0240  0.9760  40.0

[9009 rows x 7 columns]

In [158]:
for i in df.columns:
    if i not in ["Category"]:
        df[i] = pd.to_numeric(df[i])
df

Acc_x     Acc_y     Acc_z  Gyro_x  Gyro_y  Gyro_z   Set
0     0.013500  0.977000 -0.071000 -1.8904  2.4392  0.9388  30.0
1    -0.001500  0.970500 -0.079500 -1.6826 -0.8904  2.1708  30.0
2     0.001333  0.971667 -0.064333  2.5608 -0.2560 -1.4146  30.0
3    -0.024000  0.957000 -0.073500  8.0610 -4.5244 -2.0730  30.0
4    -0.028000  0.957667 -0.115000  2.4390 -1.5486 -3.6098  30.0
...        ...       ...       ...     ...     ...     ...   ...
9004 -0.048000 -1.041500 -0.076500  1.4146 -5.6218  0.2926  40.0
9005 -0.037000 -1.030333 -0.053333 -2.7684 -0.5854  2.2440  40.0
9006 -0.060000 -1.031000 -0.082000  2.8416 -5.1342 -0.1220  40.0
9007 -0.038667 -1.025667 -0.044667 -0.2318  0.2562  1.1220  40.0
9008 -0.044000 -1.034000 -0.059000  1.0980 -4.0240  0.9760  40.0

[9009 rows x 7 columns]

In [159]:
df = df.reset_index()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9009 entries, 0 to 9008
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   index   9009 non-null   int64  
 1   Acc_x   9005 non-null   float64
 2   Acc_y   9009 non-null   float64
 3   Acc_z   9008 non-null   float64
 4   Gyro_x  9008 non-null   float64
 5   Gyro_y  9002 non-null   float64
 6   Gyro_z  9009 non-null   float64
 7   Set     8999 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 563.2 KB


In [160]:
df = df.dropna()

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8990 entries, 0 to 9008
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   index   8990 non-null   int64  
 1   Acc_x   8990 non-null   float64
 2   Acc_y   8990 non-null   float64
 3   Acc_z   8990 non-null   float64
 4   Gyro_x  8990 non-null   float64
 5   Gyro_y  8990 non-null   float64
 6   Gyro_z  8990 non-null   float64
 7   Set     8990 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 632.1 KB


In [162]:
from sklearn.preprocessing import StandardScaler

Y = df["Set"]
X = df.drop(columns="Set")
scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train

array([[ 1.10561621, -0.00939293, -1.29482109, ..., -1.66261847,
         0.49020771,  0.08600606],
       [-0.25056426, -0.00935833, -0.87137017, ..., -2.25493298,
        -0.2317713 ,  0.16835014],
       [-0.9273087 , -0.00958133,  0.92034967, ..., -0.53282804,
         0.11358841,  0.11497842],
       ...,
       [ 0.34543226, -0.00926744,  0.65108019, ...,  0.09128153,
         0.01143351, -0.0084841 ],
       [-1.40026078, -0.00960933,  0.62696651, ...,  0.66219847,
         0.53954155,  0.06503822],
       [ 1.06985642, -0.00952786, -1.20640424, ..., -0.15990393,
         0.07396407,  0.00327972]])

In [172]:
y_train[706]

58.0

1. transform data into quantum states

In [164]:
dev = qml.device("default.qubit", wires=2)
@qml.qnode(dev)
def quantum_circuit(x):
    qml.RX(x[0], wires=0)
    qml.RY(x[1], wires=1)
    qml.CNOT(wires=[0, 1])
    return qml.probs(wires=[0, 1])

In [173]:
def q_knn(X_train, y_train, X_test, k=3):
    predictions = []
    for x_test in X_test:
        distances = []
        for x_train in X_train:
            prob = quantum_circuit(x_train)
            distances.append(prob[1])

        k_indices = np.argsort(distances)[:3]
        print(k_indices)
        k_nearest_labels = [y_train[i+1] for i in k_indices]


        most_common = np.bincount(k_nearest_labels).argmax()
        predictions.append(most_common)
    return np.array(predictions)

In [174]:
predictions = q_knn(X_train, y_train, X_test, k=3)
accuracy = accuracy_score(y_test, predictions)
print(f'Accuracy of Q-KNN: {accuracy:.2f}')

[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]
[ 705 3458 5847]


KeyboardInterrupt: 